version: '3.8'
services:
  app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      FLASK_ENV: development

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myappaks
      POSTGRES_PASSWORD: josecruz06
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: